export const data = [
  { label: "All", value: "All" },
  { label: "Historical", value: "Historical" },
  { label: "Cultural", value: "Cultural" },
  { label: "Natural", value: "Natural" },
];
export const data2 = [
  { label: "Saved", value: "Saved" },
  { label: "My Trips", value: "My Trips" },
  { label: "Setting", value: "Setting" },
];

export const cardsData = [
  {
    id: "1",
    title: "Great Pyramids of Giza",
    location: "Giza, Cairo",
    type: "Historical",
    rating: 4.9,
    reviews: 2845,
    content1: `The Great Pyramids of Giza stand as one of the Seven Wonders of the Ancient World, built more than 4,500 years ago as eternal tombs for the Pharaohs. Their massive limestone structures reflect Egypt’s extraordinary architectural genius.`,
    content2: `Visitors are amazed by the size and precision of these monumental constructions. Standing before the Great Pyramid, it’s easy to feel the mystery and greatness of ancient Egyptian civilization.`,
    content3: `A visit to Giza is more than just sightseeing — it’s a journey through time, connecting you with the legacy of kings, gods, and the timeless sands of Egypt.`,
    img: "https://images.unsplash.com/photo-1525604529863-915380184a43",
  },
  {
    id: "2",
    title: "Luxor Temple",
    location: "Luxor",
    type: "Historical",
    rating: 4.8,
    reviews: 1923,
    content1: `The Luxor Temple, located on the east bank of the Nile, is one of the most magnificent monuments of ancient Thebes. It was dedicated to the rejuvenation of kingship and the god Amun.`,
    content2: `As you walk through the grand colonnades and beautifully carved hieroglyphs, you can almost hear the echoes of ceremonies and processions that once filled the temple.`,
    content3: `At night, the temple comes alive under golden lights, creating an unforgettable spiritual and historical experience.`,
    img: "https://images.unsplash.com/photo-1682403010342-477107a5c329",
  },
  {
    id: "3",
    title: "Red Sea Beaches",
    location: "Hurghada",
    type: "Natural",
    rating: 4.7,
    reviews: 1567,
    content1: `The Red Sea beaches of Hurghada are a paradise for divers and sun lovers, known for their crystal-clear waters and vibrant coral reefs.`,
    content2: `Whether you’re snorkeling among colorful fish, enjoying water sports, or relaxing on golden sands, the Red Sea offers an unmatched escape from daily life.`,
    content3: `With year-round sunshine and breathtaking marine life, Hurghada stands as one of the most beautiful coastal destinations in Egypt.`,
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
  },
  {
    id: "4",
    title: "Abu Simbel Temples",
    location: "Aswan",
    type: "Historical",
    rating: 4.9,
    reviews: 2134,
    content1: `Carved into solid rock, the Abu Simbel Temples are a masterpiece of ancient Egyptian engineering built by Pharaoh Ramses II to honor himself and the gods.`,
    content2: `The massive statues guarding the entrance are awe-inspiring, and the precise alignment with the sun during the biannual solar festival shows the genius of its builders.`,
    content3: `A visit to Abu Simbel is a journey to witness human creativity, devotion, and the eternal power of ancient Egypt.`,
    img: "https://images.unsplash.com/photo-1666593198332-127af3e3536d",
  },
  {
    id: "5",
    title: "Egyptian Museum",
    location: "Cairo",
    type: "Cultural",
    rating: 4.8,
    reviews: 2456,
    content1: `The Egyptian Museum in Cairo is home to the world’s most extensive collection of ancient Egyptian artifacts, including treasures from the tomb of Tutankhamun.`,
    content2: `Walking through its halls is like stepping into the pages of history, surrounded by mummies, golden statues, and royal jewelry that tell stories of an incredible civilization.`,
    content3: `It’s an essential stop for anyone seeking to explore the cultural and artistic legacy of Egypt’s past.`,
    img: "https://images.unsplash.com/photo-1710803622349-0a17829918c5",
  },
  {
    id: "6",
    title: "Cairo Citadel",
    location: "Cairo",
    type: "Historical",
    rating: 4.6,
    reviews: 1789,
    content1: `The Cairo Citadel, built by Salah ad-Din in the 12th century, stands proudly overlooking the city as a symbol of strength and history.`,
    content2: `Inside, you’ll find the stunning Mosque of Muhammad Ali, impressive museums, and breathtaking views of Cairo’s skyline.`,
    content3: `A walk through the Citadel combines architecture, history, and spirituality — offering a perfect blend of Egypt’s medieval and Islamic heritage.`,
    img: "https://images.unsplash.com/photo-1573814324266-5d2832261fb9",
  },
  {
    id: "7",
    title: "Karnak Temple",
    location: "Luxor",
    type: "Historical",
    rating: 4.9,
    reviews: 2678,
    content1: `The Karnak Temple complex is one of the largest religious sites ever built, dedicated primarily to the god Amun-Ra.`,
    content2: `Its grand hypostyle hall with towering columns and intricate hieroglyphs reveals the immense devotion and artistry of ancient Egyptian priests and builders.`,
    content3: `Visiting Karnak is like entering the spiritual heart of ancient Egypt — a breathtaking reminder of human creativity and faith.`,
    img: "https://images.unsplash.com/photo-1710659765212-835adf573927",
  },
  {
    id: "8",
    title: "Valley of the Kings",
    location: "Luxor",
    type: "Historical",
    rating: 4.8,
    reviews: 2234,
    content1: `The Valley of the Kings served as the royal burial ground for Egypt’s pharaohs, including the famous tomb of Tutankhamun.`,
    content2: `Each tomb is beautifully decorated with colorful hieroglyphs that depict the pharaoh’s journey to the afterlife.`,
    content3: `Exploring the valley is an awe-inspiring experience — a place where history, art, and mystery meet beneath the desert hills.`,
    img: "https://images.unsplash.com/photo-1682403010342-477107a5c329",
  },
  {
    id: "9",
    title: "Nile River Cruise",
    location: "Aswan to Luxor",
    type: "Natural",
    rating: 4.7,
    reviews: 1890,
    content1: `A Nile River Cruise offers a unique way to explore Egypt’s ancient wonders while sailing along the world’s longest river.`,
    content2: `From sunrise views over the temples to traditional Nubian villages and vibrant sunsets, every moment on the Nile feels timeless.`,
    content3: `Combining comfort, culture, and breathtaking scenery, the cruise is one of the most magical experiences you can have in Egypt.`,
    img: "https://images.unsplash.com/photo-1718728593363-32feff215393",
  },
];
